export const COMPANY_INFO = {
  name: "EuroTech Solutions",
  tagline: "Innovative Software Solutions for European Businesses",
  description:
    "Leading software development company serving the European Union with cutting-edge web applications, mobile solutions, and enterprise software.",
  email: "contact@eurotechsolutions.eu",
  phone: "+49 30 12345678",
  address: "Alexanderplatz 1, 10178 Berlin, Germany",
  founded: 2018,
  employees: "50+",
  projects: "200+",
  countries: "15+",
};

export const EU_COUNTRIES = [
  "Austria",
  "Belgium",
  "Bulgaria",
  "Croatia",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Estonia",
  "Finland",
  "France",
  "Germany",
  "Greece",
  "Hungary",
  "Ireland",
  "Italy",
  "Latvia",
  "Lithuania",
  "Luxembourg",
  "Malta",
  "Netherlands",
  "Poland",
  "Portugal",
  "Romania",
  "Slovakia",
  "Slovenia",
  "Spain",
  "Sweden",
];

export const SERVICES_DATA = [
  {
    id: "web-development",
    title: "Web Development",
    description: "Custom web applications built with modern technologies",
    icon: "🌐",
    features: [
      "React/Vue/Angular",
      "Node.js/Python/PHP",
      "Cloud Deployment",
      "API Integration",
    ],
    price: "From €5,000",
  },
  {
    id: "mobile-development",
    title: "Mobile Development",
    description: "Native and cross-platform mobile applications",
    icon: "📱",
    features: [
      "iOS/Android Native",
      "React Native",
      "Flutter",
      "App Store Publishing",
    ],
    price: "From €8,000",
  },
  {
    id: "enterprise-software",
    title: "Enterprise Software",
    description: "Scalable business solutions and ERP systems",
    icon: "🏢",
    features: [
      "Custom ERP/CRM",
      "Database Design",
      "System Integration",
      "Legacy Migration",
    ],
    price: "From €15,000",
  },
  {
    id: "cloud-solutions",
    title: "Cloud Solutions",
    description: "AWS, Azure, and Google Cloud implementations",
    icon: "☁️",
    features: [
      "Cloud Migration",
      "DevOps & CI/CD",
      "Serverless Architecture",
      "Container Orchestration",
    ],
    price: "From €3,000",
  },
  {
    id: "ai-ml",
    title: "AI & Machine Learning",
    description: "Intelligent solutions powered by artificial intelligence",
    icon: "🤖",
    features: [
      "Predictive Analytics",
      "Natural Language Processing",
      "Computer Vision",
      "Chatbots",
    ],
    price: "From €10,000",
  },
  {
    id: "consulting",
    title: "IT Consulting",
    description: "Strategic technology consulting and digital transformation",
    icon: "💡",
    features: [
      "Digital Strategy",
      "Technology Audit",
      "Architecture Design",
      "Team Training",
    ],
    price: "From €150/hour",
  },
];
